[package]
name = "nanotracer-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = "0.32"
image = "0.25"
clap = { version = "4.6", features = ["derive"] }
exr = "1.74"
fastrand = "2.4"
num_cpus = "1.17"
rtbvh = "0.6.2"
ash = "0.38"
shaderc = "0.10"
bytemuck = { version = "1.25", features = ["derive"] }
indicatif = "0.18"
gltf = "1.4"
